import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'mamad',
      email: 'mamad@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'boyka',
      email: 'boyka@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Base Cap GreenZone',
      slug: 'base-cap',
      category: 'Shirts',
      image: '/images/1.jpg',
      isFeatured: true,
      featuredImage: '/images/banner1.jpg',
      price: 70,
      brand: 'UF PRO',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Mindset Tshirt',
      slug: 'mindset-tshirt',
      category: 'Shirts',
      image: '/images/5.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 80,
      brand: 'UF PRO',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Delta Ace plus',
      slug: 'delta-ace',
      category: 'Shirts',
      image: '/images/3.jpg',
      isFeatured: true,
      featuredImage: '/images/banner3.jpg',
      price: 90,
      brand: 'UF PRO',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Striker Ht Combat',
      slug: 'striker-combat',
      category: 'UF PRO',
      image: '/images/4.jpg',
      isFeatured: true,
      featuredImage: '/images/banner4.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking pants',
    },
    {
      name: 'Belt Buckle',
      slug: 'belt-buckle',
      category: 'UF PRO',
      image: '/images/2.jpg',
      price: 95,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Striker Delta',
      slug: 'striker-delta',
      category: 'UF PRO',
      image: '/images/6.jpg',
      price: 75,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
  ],
};
export default data;
